# Generated by Django 3.2.9 on 2021-12-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackitapi', '0002_alter_applicant_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='industry',
            field=models.CharField(max_length=50),
        ),
    ]
